# Generated by Django 5.1.4 on 2025-02-04 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideaGen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_id", models.CharField(max_length=100)),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ideaGen.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "module_id")},
            },
        ),
    ]
