# Generated by Django 5.1.4 on 2025-02-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ideaGen", "0002_projectmodule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectModule",
        ),
    ]
