# Generated by Django 5.1.4 on 2025-02-04 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="main_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_histories",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="chat_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chathistory",
            ),
        ),
        migrations.AddField(
            model_name="conversationmemorybuffer",
            name="conversation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory_buffer",
                to="chat.chathistory",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="main_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_documents",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="documents",
            field=models.ManyToManyField(
                blank=True, related_name="chat_histories", to="chat.document"
            ),
        ),
        migrations.AddField(
            model_name="processedindex",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="chat.document"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
