# Generated by Django 5.1.4 on 2025-02-04 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        ("ideaGen", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ideageneratormodule",
            name="product_ideas",
            field=models.ManyToManyField(
                related_name="project_modules", to="ideaGen.productidea2"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="projectmodule",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="ideageneratormodule",
            name="project_module",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idea_generator",
                to="core.projectmodule",
            ),
        ),
        migrations.AddField(
            model_name="documentqamodule",
            name="project_module",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_qa",
                to="core.projectmodule",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmodule",
            unique_together={("project", "module_type")},
        ),
    ]
